### ISSUE TITLE
Promote-skjermbildet: mister kontekst ved refresh

### ISSUE THREAD

**Issue by Quist** [navikt/fo-forenklet-deploy#15]
Hvis man går rett inn, eller refresher, på url'en for promote så mister man konteksten av mellom hvilke to versjoner man skal diffe. Ser ut som den da defaulter til å hente inn alle endringer

``` https://forenklet-deploy.nais.preprod.local/promote/modiabrukerdialog/t6 ```

Mulig løsning er kanskje å flytte konteksten som en url-parameter?

**Comment by etse** [comment]
Er noe feil ved henting av data, ser restkallet blir sendt med parametre `fromVersion=null&toVersion=null`
Den må hente ut versjonsnummer før den kan hente commits, det blir tydeligvis gjort samtidig.
