### ISSUE TITLE
Automatisk generere releasenote i confluence

### ISSUE THREAD

**Issue by etse** [navikt/fo-forenklet-deploy#19]
Som ansvarlig for utrulling i produksjon
Ønkser jeg at releasenoten blir automatisk generert i confluence
Slik at jeg kan bruke tiden min på andre oppgaver
Og redusere sansynligheten for at release-noten inneholder feil

-------------------

Gitt at jeg går inn på go/nogo siden
Når jeg velger applikasjoner som er go for produksjon
Skal jeg få opp en kvittering med oppsummering av releasen
Og få en knapp for å legge releasenoten i confluence

Gitt at jeg er på kvitteringsiden
Når jeg trykker på "Lag release-note"
Skal det opprettes et dokument i confluence som følger standardmal
Og jeg skal få opp releasenoten i ett nytt vindu

Gitt at jeg er på kvitteringssiden
Når jeg trykker på "Lag release-note"
Skal det opprettes et dokuement som følger standardmal
Og det skal være en rad per applikasjon
Og den skal være fyllt ut med versjonsnummer som skal i produksjon
Og hver applikasjon skal ha liste med relaterte Jira-issues for deploy
Og resterende felter skal være blanke for manuell utfylling

**Comment by bentejohansson** [comment]
Denne featuren er ikke nødvendig lengre for FO. Jeg foreslår at denne lukkes.
