### ISSUE TITLE
Kunne velge hvilke miljøer som skal vises på go/nogo

### ISSUE THREAD

**Issue by etse** [navikt/fo-forenklet-deploy#5]
Det er ønskelig å kunne velge mellom hvilke 2 miljøer man ser en diff. Dette kan gjøres ved å f.eks. lage 2 dropdowns for å velge fra og til miljø.

**Comment by Quist** [comment]
+1 på det behovet :) Tenker du en egen page man går inn på, eller som endel av eksisterende?

**Comment by bentejohansson** [comment]
Ønsker veldig denne funksjonaliteten.

**Comment by etse** [comment]
Dette skal nå være lagt til. Bare å trykke på "Promotering" i menylinjen i hodet.
